In [8]:
import numpy as np


# PHLI BAAT TO YEH HAI KI HM JIN BHI DATA KO ARRAY ME CONVERT KAR RHE HOTE HAI WAH YA TO
# LIST HONGE YA PHIR TUPPLE
# MTLB HM NP.ARRAY() ME LIST TYPE DATA YA PHIR TUPPLE TYPE DATA PASS KR RHE HOTE HAI

In [9]:
list = [1,2,3,4,5]

In [10]:
#                     HOW TO CONVERT A DATA INTO AN ARRAY SEE the syntax below

np.array(list)
# np.array() or 
# np.asarray() or 
# np.asanyarray() all are same syntax

# ab chaho to isko ek reference me store kra skte hai for further uses

arr = np.array(list)

# how to know that array 1D hai ya phir 2D 3D to know this see the array data if data is under,
# single square bracket then it is a 1D array so we can say that
# one [] bracket --->> 1D array
# two [] bracket --->> 2D array
# three [] bracket --->> 3D array

#                  NOTE so basically a numpy create an array


In [11]:
arr

array([1, 2, 3, 4, 5])

In [12]:
#                  NOW HOW TO GET DATA AS 1D 2D AND 3D IN ARRAY SEE

# for 1D 
# np.array("pass the data here")

# for 2D 
# np.array(['pass the data here'])

# for 3D 
# np.array([['pass the data here']])

In [13]:
#                    NOTE ----->>>

# matrix ek 2D array hi hota hai so matrix is a subset of an array so we can convert our data,
# into matrix jo ki ek 2D array hi hoga see

mat = np.matrix(list)
mat


matrix([[1, 2, 3, 4, 5]])

In [14]:
type(mat)

numpy.matrix

In [15]:
#                    HOW TO CREATE AN ARRAY
import numpy as np

# Create a 1D array
arr1d = np.array([1, 2, 3, 4, 5])
print(arr1d)

# Create a 2D array
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr2d)

# Create a 3D array
arr3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print(arr3d)


[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [16]:
#                 HOT TO ACCESS ELEMENTS FORM ANY ARRAY SEEE BELOW COLUMNS

In [17]:
arr1d

array([1, 2, 3, 4, 5])

In [18]:
arr1d[0]

1

In [19]:
arr[1][2]

IndexError: invalid index to scalar variable.

In [20]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
arr2d[1][2]

6

In [22]:
arr3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [23]:
arr3d[0][1][1]

4

In [24]:
#            representation of 1D 2D and 3D data jisko hm array bhi bol rhe hote hai see

In [25]:
# [1,2,3,4,5] --->> 1D

# [[1,2,3,4,5],
#  [1,2,3,4,5],  OR [[1,2,3,4],[1,2,3,4],[1,2,3,4]] ------->>>> 2D FOR 3D JUST IMAGINE
#  [1,2,3,4,5]]

In [26]:



#                   SOME IMPORTANT FUNCTION IN NUMNPY SEE BELOW COLUMNS




In [27]:
#1.np.array() 
# Creates a NumPy array from a list or tuple.



import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)


[1 2 3 4 5]


In [28]:
# np.arange() 

# Creates a NumPy array with evenly spaced values within a given interval
import numpy as np

arr = np.arange(0, 10, 2)
print(arr)


[0 2 4 6 8]


In [29]:
# np.zeros() - Creates a NumPy array filled with zeros.

arr = np.zeros((2, 3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [30]:
# np.ones() - Creates a NumPy array filled with ones.

arr = np.ones((2, 3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [34]:
np.ones(2)

array([1., 1.])

In [36]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [31]:
# np.linspace() - Creates a NumPy array with evenly spaced values within a given range.

arr = np.linspace(0, 1, 5)
print(arr)

[0.   0.25 0.5  0.75 1.  ]


In [32]:
# np.random.rand() - Creates a NumPy array with random values between 0 and 1.

arr = np.random.rand(2, 3)
print(arr)

[[0.97983347 0.85300793 0.11378571]
 [0.70511425 0.04135948 0.08746913]]


In [33]:
# np.random.rand() - Creates a NumPy array with random values between 0 and 1.


arr = np.random.rand(2)
print(arr)

[0.85678138 0.31830928]


In [39]:
# mtlb 1 se 10 ke bich 3 by 4 ka ek array banana hai

arr5 = np.random.randint(1,10,(3,4))
arr5

array([[7, 1, 8, 4],
       [8, 2, 7, 1],
       [1, 5, 8, 1]])

In [40]:
#                       NOTE

#  SO BASICALLY HM KISI BHI ARRAY KO DATAFRAME ME BHI CONVERT KR SKTE HAI

import pandas as pd

arr6 = pd.DataFrame(arr5)
arr6

0  1  2  3
0  7  1  8  4
1  8  2  7  1
2  1  5  8  1

In [ ]:
#               np.reshape() function


# yeh function data ki bina change kiye kisi bhi array ka shape bole row and column 
# chan ge krdega see below column
# but row * column should same in both cases 

In [41]:
arr5

array([[7, 1, 8, 4],
       [8, 2, 7, 1],
       [1, 5, 8, 1]])

In [47]:
arr5.reshape(2,6)

array([[7, 1, 8, 4, 8, 2],
       [7, 1, 1, 5, 8, 1]])

In [ ]:


#                   <<--------NOTE--------->>

# IN CASE OF MATRIX/ARRAY ROW AND COLUMN DONO HI 0 AND 1 SE START HOTE HAI SEE BELOW COLUMN

In [48]:
arr5

array([[7, 1, 8, 4],
       [8, 2, 7, 1],
       [1, 5, 8, 1]])

In [52]:
# mtlb 1 to 2 row tak ka data do
arr5[1:3]

array([[8, 2, 7, 1],
       [1, 5, 8, 1]])

In [54]:
arr5[0]

array([7, 1, 8, 4])

In [56]:
# mtlb 0 se lekr 2 tak ke row ka 1th element lao

arr5[0:3,1]

array([1, 2, 5])

In [57]:
arr5[0,1]

1

In [59]:
arr5

array([[7, 1, 8, 4],
       [8, 2, 7, 1],
       [1, 5, 8, 1]])

In [58]:
arr5[0:3,1:3]

array([[1, 8],
       [2, 7],
       [5, 8]])

In [60]:
arr7= np.random.randint(1,20,(4,5))

In [61]:
arr7

array([[10, 12, 17,  3, 13],
       [ 5, 10, 14,  2, 13],
       [ 9,  4,  8,  5, 18],
       [ 5,  7,  3, 13, 13]])

In [62]:
arr7[arr7>10]

array([12, 17, 13, 14, 13, 18, 13, 13])

In [ ]:
# AGAR HM 1D array ki baat kre to ek 1D array ek single row ke form hoga ya phir 
# ek single column ke form me hoga

In [66]:
arr8 = np.random.randint(1,9,(6))

In [67]:
arr8

array([4, 2, 4, 5, 3, 5])

In [ ]:
# HMESHA EK 2D ARRAY HI TRANSPOSE HOTA HAI SO AGAR KOI 1D ARRAY HAI TO 
# USKO 2D BANA LENA HAI WE KNOW WELL THAT SO SEE

In [70]:
arr9 = np.array([arr8])

In [71]:
arr9

array([[4, 2, 4, 5, 3, 5]])

In [ ]:
# ab hm isko transpose kr skte hai to get a column or we can say that
# we can get 1d array as one column see

In [72]:
arr9.T

array([[4],
       [2],
       [4],
       [5],
       [3],
       [5]])

In [ ]:


#                                 BROADCASTING


# JB HM EK ARRAY ME KISI EK ROW YA COLUMN KO ADD KR RHE HOTE HAI AGAR KOI ROW HAI
# TO WAH ARRAY ME ROWISE ADD HOGA AND VICE VERSA SEE BELOW 

In [77]:
arr10 = np.random.randint(1,20,(6,6))
arr10

array([[ 7, 11, 15, 11, 17, 12],
       [ 8, 16, 12, 17,  9,  5],
       [ 8, 13, 13, 18, 17,  1],
       [ 9, 14, 13, 11,  4,  2],
       [ 5, 15,  8,  1,  1,  9],
       [12, 13,  2, 15,  1,  5]])

In [78]:
arr10 + arr9

array([[11, 13, 19, 16, 20, 17],
       [12, 18, 16, 22, 12, 10],
       [12, 15, 17, 23, 20,  6],
       [13, 16, 17, 16,  7,  7],
       [ 9, 17, 12,  6,  4, 14],
       [16, 15,  6, 20,  4, 10]])

In [79]:
arr10 + arr8

array([[11, 13, 19, 16, 20, 17],
       [12, 18, 16, 22, 12, 10],
       [12, 15, 17, 23, 20,  6],
       [13, 16, 17, 16,  7,  7],
       [ 9, 17, 12,  6,  4, 14],
       [16, 15,  6, 20,  4, 10]])

In [ ]:




#                                  NUMPY PART 2






In [ ]:
# how  a transpose work see

In [4]:
import numpy as np

arr11 = np.random.randint(1,11,(3,4))

In [5]:
arr11

array([[ 2,  2, 10,  7],
       [ 9,  9,  1,  9],
       [ 4,  7,  4,  3]])

In [6]:
# so hamare pass yha pr 3x4 ka ek array hai aur hm jaise hi array11.T krenge
# to 3x4 ki ulta krdega mtlb 4x3 ka array milega mtlb rowise elements ko uthana hai,
# aur columnwise arrange krna hai in such way that ki 4x3 ka array mil jaaye see below 

arr11.T

array([[ 2,  9,  4],
       [ 2,  9,  7],
       [10,  1,  4],
       [ 7,  9,  3]])

In [9]:
arr11.flatten()

array([ 2,  2, 10,  7,  9,  9,  1,  9,  4,  7,  4,  3])

In [11]:
# expand_dims() function ------>> yah 1d ko 2d bna dega see
arr12 = np.random.randint(1,6,(5))
arr12

array([4, 2, 3, 3, 2])

In [12]:
type(arr12)

numpy.ndarray

In [14]:
np.expand_dims(arr12,axis=1)

array([[4],
       [2],
       [3],
       [3],
       [2]])

In [16]:
np.diag(arr12)

array([[4, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 2]])

In [ ]:
#                           BINARY OPERATION


# for addition ,subtraction , normal multiplication and division both array should be same shape and size
# and trhese all happen according corresponding indices but for matrix multiplication we use @ 
# and column of first array should equal to second array row

In [20]:
arr13 = np.random.randint(1,9,(3,4))
arr13

array([[2, 6, 1, 5],
       [2, 4, 6, 4],
       [2, 1, 6, 5]])

In [25]:
arr14 = np.random.randint(1,9,(3,4))
arr14

array([[5, 7, 3, 5],
       [8, 3, 2, 6],
       [8, 3, 3, 7]])

In [26]:
arr13 + arr14

array([[ 7, 13,  4, 10],
       [10,  7,  8, 10],
       [10,  4,  9, 12]])

In [27]:
arr13- arr14

array([[-3, -1, -2,  0],
       [-6,  1,  4, -2],
       [-6, -2,  3, -2]])

In [28]:
arr13*arr14

array([[10, 42,  3, 25],
       [16, 12, 12, 24],
       [16,  3, 18, 35]])

In [29]:
arr13/arr14

array([[0.4       , 0.85714286, 0.33333333, 1.        ],
       [0.25      , 1.33333333, 3.        , 0.66666667],
       [0.25      , 0.33333333, 2.        , 0.71428571]])

In [30]:
arr13%arr14

array([[2, 6, 1, 0],
       [2, 1, 0, 4],
       [2, 1, 0, 5]])

In [31]:
arr13**arr14

array([[    32, 279936,      1,   3125],
       [   256,     64,     36,   4096],
       [   256,      1,    216,  78125]])

In [32]:
arr13 @ arr14

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)

In [34]:




#                              string function




# tmlb agr hm kisi string data waale aaray pr operation chahte hai to call char see below

arr15 = np.array(['creator','sanit'])
arr15

array(['creator', 'sanit'], dtype='<U7')

In [36]:
np.char.upper(arr15)

array(['CREATOR', 'SANIT'], dtype='<U7')

In [37]:
np.char.lower(arr15)

array(['creator', 'sanit'], dtype='<U7')

In [38]:
np.char.title(arr15)

array(['Creator', 'Sanit'], dtype='<U7')

In [ ]:


#                                trignometric function



In [39]:
arr16 = np.random.randint(1,9,(4,5))
arr16

array([[6, 3, 1, 2, 7],
       [6, 2, 5, 3, 5],
       [2, 5, 7, 4, 2],
       [5, 8, 7, 7, 3]])

In [40]:
np.sin(arr16)

array([[-0.2794155 ,  0.14112001,  0.84147098,  0.90929743,  0.6569866 ],
       [-0.2794155 ,  0.90929743, -0.95892427,  0.14112001, -0.95892427],
       [ 0.90929743, -0.95892427,  0.6569866 , -0.7568025 ,  0.90929743],
       [-0.95892427,  0.98935825,  0.6569866 ,  0.6569866 ,  0.14112001]])

In [41]:
np.tan(arr16)

array([[-0.29100619, -0.14254654,  1.55740772, -2.18503986,  0.87144798],
       [-0.29100619, -2.18503986, -3.38051501, -0.14254654, -3.38051501],
       [-2.18503986, -3.38051501,  0.87144798,  1.15782128, -2.18503986],
       [-3.38051501, -6.79971146,  0.87144798,  0.87144798, -0.14254654]])

In [42]:
np.power(arr16,2)

array([[36,  9,  1,  4, 49],
       [36,  4, 25,  9, 25],
       [ 4, 25, 49, 16,  4],
       [25, 64, 49, 49,  9]])

In [43]:
np.exp(arr16)

array([[4.03428793e+02, 2.00855369e+01, 2.71828183e+00, 7.38905610e+00,
        1.09663316e+03],
       [4.03428793e+02, 7.38905610e+00, 1.48413159e+02, 2.00855369e+01,
        1.48413159e+02],
       [7.38905610e+00, 1.48413159e+02, 1.09663316e+03, 5.45981500e+01,
        7.38905610e+00],
       [1.48413159e+02, 2.98095799e+03, 1.09663316e+03, 1.09663316e+03,
        2.00855369e+01]])

In [44]:
np.log(arr16)

array([[1.79175947, 1.09861229, 0.        , 0.69314718, 1.94591015],
       [1.79175947, 0.69314718, 1.60943791, 1.09861229, 1.60943791],
       [0.69314718, 1.60943791, 1.94591015, 1.38629436, 0.69314718],
       [1.60943791, 2.07944154, 1.94591015, 1.94591015, 1.09861229]])

In [45]:
np.mean(arr16)

4.5

In [46]:
np.median(arr16)

5.0

In [47]:
np.min(arr16)

1

In [48]:
np.max(arr16)

8

In [ ]:
#                         <<------------NOTE----------->>



# SO OVERALL FINALLY WE CAN SAY THAT NUMPY SI BASICALLY FOR COMPUTING OF NUMERICAL DATA,
# SO JUST SEARCH THE  FUNCTION JISKO APPLY KRNA HAI 
# BKOZ HAR TYPE KE FUNCTION AVAILABLE HAI IN NUMPY FOR DATA MANIPULATION OR COMPUTING

In [ ]:




#                              SORTING , SEARCHING AND  COUNTING FUNCTION




In [ ]:
# Sorting, searching, and counting are three important functions in computer science and data analysis. Here's a brief explanation of each:

# 1.Sorting: Sorting refers to arranging a collection of items or data in a specific order, 
# such as ascending or descending order. The goal of sorting is to make it easier to search and retrieve information from the data. 
# There are various algorithms for sorting data, such as bubble sort, quick sort, and merge sort.

# 2.Searching: Searching refers to looking for a specific item or data within a collection or dataset.
# The goal of searching is to find the desired item as efficiently as possible. There are various algorithms for searching data,
# such as linear search, binary search, and interpolation search.

# 3.Counting: Counting refers to determining the number of occurrences of a specific item or data within a collection or dataset.
# Counting is useful in many applications, such as in analyzing data frequency, detecting anomalies or patterns, and identifying trends.

# These three functions are often used together in data analysis and manipulation tasks. 
# For example, we might first sort a dataset, then search for specific items within it, and finally count the occurrences of those items.

In [4]:
import numpy as np

array20 = np.array([1,6,3,9,5,8,7])

In [5]:
array20

array([1, 6, 3, 9, 5, 8, 7])

In [6]:
# yah function data ko ascending ya descending order me arrange krdega see
np.sort(array20)

array([1, 3, 5, 6, 7, 8, 9])

In [9]:
# yah function yah batata hai ki ek sort array me koi value kha jaane waali hai see so basically it give index of that value
a = np.searchsorted(array20,2)

In [10]:
a

1

In [12]:
# yah function condition ke base pr batayega ki values kis kis indices pr available hai
np.where(array20>6)

(array([3, 5, 6]),)

In [14]:
np.extract(array20>4,array20)

array([6, 9, 5, 8, 7])

In [ ]:
# we can also produce matrix instead of array jo ki khud ek array hi hota hai see 

import numpy.matlib as np

In [15]:
np.matrix([1,2,3,4,5])

matrix([[1, 2, 3, 4, 5]])